// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cysjaamnokdmmcdlecuc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN5c2phYW1ub2tkbW1jZGxlY3VjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5NjY5NzMsImV4cCI6MjA3MjU0Mjk3M30.lubX2mWCoY2OkSrlfhN_9-n9w-l9iBPVYRsLfJ88o7g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});